name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - uses: actions/checkout@v4 
     with:
       fetch-depth: 0
       ref: gh-pages
   - name: restore timestamps
     uses: chetan/git-restore-mtime-action@v2
   - name: Checkout siterebuild
     uses: actions/checkout@v4
     with:
      repository:  michal-h21/siterebuild 
      path: siterebuild
   - uses: xu-cheng/texlive-action/full@v1
     with:
       run: |
         cd texposts
         ./rebuild.sh
   - name: Publish the web pages
     uses: peaceiris/actions-gh-pages@v3
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./docs
       publish_branch: gh-pages
       enable_jekyll: true
