name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - uses: actions/checkout@v4 
     with:
       fetch-depth: 0
   # - name: Setup python # it seems that "restore timestamps" needs Python 2
   #   uses: actions/setup-python@v2
   #   with:
   #     python-version: "2.x"
   - name: restore timestamps
     uses: chetan/git-restore-mtime-action@v2
   - name: Checkout siterebuild
     uses: actions/checkout@v4
     with:
      repository:  michal-h21/siterebuild 
      path: siterebuild
   - uses: xu-cheng/texlive-action/full@v1
     with:
       run: |
         cd texposts
         ./rebuild.sh
   # - name: Run make4ht 
   #   uses: docker://ghcr.io/michal-h21/make4ht-action:latest 
   #   env: # we must go to the directory with tex posts and execute siterebuild
   #     command: cd texposts &&  ./rebuild.sh
   #     # command: "cd texposts && ../siterebuild/siterebuild -l debug && ls -lt blogging-in-latex-2021-edition && ls -lt ../docs/_posts/" 
   - name: Autocommit generated files
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
       commit_message: Save generated files
       file_pattern: docs/*