name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - name: Checkout main branch
     uses: actions/checkout@v4
     with:
       fetch-depth: 0
   
   - name: Checkout html branch
     run: |
       git fetch origin html
       git checkout html
       git config user.name "github-actions"
       git config user.email "github-actions@github.com"
   
   - name: Merge changes from main
     run: |
       git merge origin/main --no-edit --strategy-option=theirs
   
   - name: Restore timestamps
     run: |
       git ls-files -z | while read -d '' file; do
         if [ -f "$file" ]; then
           timestamp=$(git log --pretty=format:%cd -n 1 --date=iso -- "$file")
           if [ -n "$timestamp" ]; then
             touch -d "$timestamp" "$file"
           fi
         fi
       done
   
   - name: Checkout siterebuild
     uses: actions/checkout@v4
     with:
       repository: michal-h21/siterebuild 
       path: siterebuild
   
   - uses: xu-cheng/texlive-action/full@v1
     with:
       run: |
         cd texposts
         ./rebuild.sh

   - name: Pull latest changes from origin
     run: |
       git pull origin html --rebase  # nebo --no-rebase podle preference
       # nebo pro force sync:
       # git fetch origin html
       # git reset --hard origin/html 
       
   - name: Autocommit generated files
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
       commit_message: Save generated files
       file_pattern: docs/*
       branch: html
