name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - uses: actions/checkout@v4 
     with:
       fetch-depth: 0
   - name: Checkout and sync output branch
     uses: actions/checkout@v4
     with:
       ref: html
       path: output
       fetch-depth: 0
   - name: Sync output with main branch
      run: |
        cd output
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        
        # Přidat main jako remote pro merge
        git remote add main-repo ../..
        git fetch main-repo main
        
        # Merge změn z main do gh-pages (převzít změny z main)
        git merge main-repo/main --strategy-option=ours --allow-unrelated-histories --no-edit
        
        # Nebo pro konzervativnější přístup:
        # git merge main-repo/main --no-commit --allow-unrelated-histories
   
   # - name: Setup python # it seems that "restore timestamps" needs Python 2
   #   uses: actions/setup-python@v2
   #   with:
   #     python-version: "2.x"
   - name: restore timestamps
     uses: chetan/git-restore-mtime-action@v2
   - name: Checkout siterebuild
     uses: actions/checkout@v4
     with:
      repository:  michal-h21/siterebuild 
      path: siterebuild
   - uses: xu-cheng/texlive-action/full@v1
     with:
       run: |
         cd texposts
         ./rebuild.sh
   # - name: Run make4ht 
   #   uses: docker://ghcr.io/michal-h21/make4ht-action:latest 
   #   env: # we must go to the directory with tex posts and execute siterebuild
   #     command: cd texposts &&  ./rebuild.sh
   #     # command: "cd texposts && ../siterebuild/siterebuild -l debug && ls -lt blogging-in-latex-2021-edition && ls -lt ../docs/_posts/" 
   - name: Autocommit generated files
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
       commit_message: Save generated files
       file_pattern: docs/*
