name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout main branch with sources
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        path: main

    - name: Restore timestamps
      uses: chetan/git-restore-mtime-action@v2
      with:
        working-directory: main

    # 2. Checkout build branch with previously generated HTML
    - name: Checkout build branch
      uses: actions/checkout@v4
      with:
        ref: build
        path: build
        fetch-depth: 0

    # 3. Copy previous HTML output to main working directory
    - name: Import old HTML posts from build branch
      run: |
        mkdir -p main/docs/_posts
        cp -r build/docs/_posts/* main/docs/_posts/ || true

    # 4. Checkout siterebuild repo
    - name: Checkout siterebuild
      uses: actions/checkout@v4
      with:
        repository: michal-h21/siterebuild
        path: siterebuild

    # 5. Run rebuild (in main working dir)
    - name: Rebuild updated LaTeX files
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          cd main/texposts
          ./rebuild.sh

    # 6. Commit new HTML files to build branch
    - name: Commit updated HTML to build branch
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        repository: build
        file_pattern: docs/_posts/*
        commit_message: "Update generated HTML blog posts"
        push_options: '--force'

    # 7. Deploy to GitHub Pages (using peaceiris)
    - name: Deploy site to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs
        publish_branch: gh-pages
        enable_jekyll: true
