name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - uses: actions/checkout@v4 
     with:
       fetch-depth: 0
   - name: Checkout and sync output branch
     uses: actions/checkout@v4
     with:
       ref: html
       path: output
       fetch-depth: 0
   - name: Sync output with main branch
     run: |
       cd output
       git config user.name "github-actions"
       git config user.email "github-actions@github.com"

       # Přidat main jako remote
       git remote add main-repo "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
       git fetch main-repo main
        
       # Přepnout na větev html a merge změn z main
       git checkout html
       git merge main-repo/main --no-edit --strategy-option=theirs
       
       # Push změn
       git push origin html
   - name: restore timestamps
     uses: chetan/git-restore-mtime-action@v2
   - name: Checkout siterebuild
     uses: actions/checkout@v4
     with:
      repository: michal-h21/siterebuild 
      path: siterebuild
   - uses: xu-cheng/texlive-action/full@v1
     with:
       run: |
         cd texposts
         ./rebuild.sh
   - name: Autocommit generated files
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
       commit_message: Save generated files
       file_pattern: docs/*
       branch: html